[package]
name = "worker"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = "0.32.5"
redis-client = {path = "../redis-client"}
store= { path = "../store"}
tokio = {version = "1.47.1" , features = ["full"]}
dotenvy = "0.15.7"
anyhow = "1.0.99"
reqwest = "0.12.23"
